<?php
session_start();

if (isset($_GET['lang'])) {
    $language = $_GET['lang'];
    $_SESSION['lang'] = $language;
} else {
    $language = isset($_SESSION['lang']) ? $_SESSION['lang'] : 'en';
}

switch ($language) {
    case 'en':
        $langStrings = [
            'hi' => 'Hi',
            'home' => 'Home',
            'switch' => 'Farmer/Seller',
            'request' => 'Request Product',
            'orders' => 'My Orders',
            'notifications' => 'New notifications',
            'cart' => 'My Cart',
            'inbox' => 'Inbox',
            'profile' => 'My Profile',
            'logout' => 'Logout',
            'login' => 'Login',
            'register' => 'Register',
            'wishlist' => 'My Wishlist',
            'wish' => 'My Wishlist',
            'add_to_wish' => 'Add to wishlist',
            'added_to_wish' => 'Added to wishlist',
            'language' => 'Language',
            'welcome' => 'Welcome to',
            'order_now' => 'Order Now',
            'not_reg' => 'Not registered?',
            'create_acc' => 'Create an account',
            'login_acc' => 'Login to your account',
            ///////////////////////////////////////////
            'join_us' => 'Join us in fostering a community of sustainable living and mindful eating',
            'latest' => 'Latest Product Listings',
            'easy' => 'Easiest way to order your freshies among these top 6 products',
            'may_like' => 'Products you may like',
            'easy_way' => 'Easiest way to order your favourites',
            'available' => 'Available',
            'search' => 'Search for products...',
            'was' => 'was',
            'now' => 'now',
            'off' => 'off',
            'order_now' => 'Order Now',
            'featured' => 'Featured Farmers & Markets',
            'view_all' => 'View All Products',
            'email_address' => 'Email Address',
            'phone' => 'Phone Number',
            'hours' => 'Operating Hours',
            'days' => 'Days of Operation',
            'farm_size' => 'Farm Size',
            'physical_add' => 'Physical Address',
            'from' => 'From',
            'in' => 'in',
            'dayss' => 'days',
            'deliv_add' => 'Delivery Address',
            'fee' => 'Fee',
            'deliv' => 'Delivery Place:',
            'freedeliv' => 'Free delivery if you purchase items costing over',
            'manual' => 'User Manual',
            // Add all the strings you need to translate
        ];
        break;
    case 'sw':
        $langStrings = [
            'hi' => 'Sawubona',
            'home' => 'Ekhaya',
            'switch' => 'Umlimi/Umtsengisi',
            'request' => 'Cela Umkhicito',
            'orders' => 'Ema Order ami',
            'notifications' => 'weTatiso letinsha',
            'cart' => 'Lengikutsenga nyalo',
            'inbox' => 'Imilayeto',
            'profile' => 'Mine',
            'logout' => 'Phuma',
            'login' => 'Ngena',
            'register' => 'Bhalisa',
            'wishlist' => 'Lengifise kukutsenga ngalelinye lilanga',
            'wish' => 'Lengikufisile',
            'add_to_wish' => 'Faka etifisweni',
            'added_to_wish' => 'Kufakiwe etifisweni',
            ////////////////////////////////////
            'not_reg' => 'Awukabhalisi?',
            'create_acc' => 'Bhalisa',
            'login_acc' => 'Ngena ku-Akhawunti yakho',
            'from' => 'Kusukela',
            
///////////////////////
            'language' => 'Lulwimi',
            'welcome' => 'Wemukelekile e-',
            'join_us' => 'Hlanganyela natsi ekhwakheni ummango wekuphila lokungiko nekudla lokucatjangiswe kabanti',
            'latest' => 'Imikhicito Yakulamalanga',
            'easy' => 'Indlela lelula yekutsenga imikhicito kulena lesitfupha kuleminye leminyenti',
            'may_like' => 'Imikhicito longayitsandza',
            'easy_way' => 'Indlela lelula yekutsenga tintfo lotitsandzako',
            'available' => 'Lokukhona',
            'search' => 'Cinga imikhicito...',
            'was' => 'bekungu',
            'now' => 'nyalo',
            'off' => 'sephulo',
            'order_now' => 'Tsenga',
            'featured' => 'Balimi neTimakethe',
            'view_all' => 'Bona yonkhe imikhicito',
            'email_address' => 'Likheli Lembane',
            'phone' => 'Inombolo yelucingo',
            'hours' => 'Ema Awa ekusebenta',
            'days' => 'Emalanga Ekusebenta',
            'farm_size' => 'Bhukhulu bendawo yekulima',
            'physical_add' => 'Likheli lemlimi',
            'in' => 'ku',
            'dayss' => 'Wemalanga',
            'deliv_add' => 'Sikuletsela lapha',
            'fee' => 'ngalemali',
            'deliv' => 'Sikuletsela lapha:',
            'freedeliv' => 'Sikuletsela mahhala nawutsenge lokungetulu kwa-',
            'manual' => 'Lusito',
            // Add all the strings you need to translate
        ];
        break;
    // Add more languages as needed
    default:
        $langStrings = [
            'hi' => 'Hi',
            'home' => 'Home',
            'switch' => 'Farmer/Seller',
            'request' => 'Request Product',
            'orders' => 'My Orders',
            'notifications' => 'New notifications',
            'cart' => 'My Cart',
            'inbox' => 'Inbox',
            'wishlist' => 'My Wishlist',
            'wish' => 'My Wishlist',
            'add_to_wish' => 'Add to wishlist',
            'added_to_wish' => 'Added to wishlist',
            'profile' => 'My Profile',
            'logout' => 'Logout',
            'not_reg' => 'Not registered?',
            'create_acc' => 'Create an account',
            'login_acc' => 'Login to your account',
            ///////////////////////////////////////////////
            'register' => 'Register',
            'login' => 'Login',
            'language' => 'Language',
            'welcome' => 'Welcome to',
            'order_now' => 'Order Now',
            'join_us' => 'Join us in fostering a community of sustainable living and mindful eating',
            'latest' => 'Latest Product Listings',
            'easy' => 'Easiest way to order your freshies among these top 6 products',
            'may_like' => 'Products you may like',
            'easy_way' => 'Easiest way to order your favourites',
            'available' => 'Available',
            'search' => 'Search for products...',
            'was' => 'was',
            'now' => 'now',
            'off' => 'off',
            'order_now' => 'Order Now',
            'featured' => 'Featured Farmers & Markets',
            'view_all' => 'View All Products',
            'email_address' => 'Email Address',
            'phone' => 'Phone Number',
            'hours' => 'Operating Hours',
            'days' => 'Days of Operation',
            'farm_size' => 'Farm Size',
            'physical_add' => 'Physical Address',
            'from' => 'From',
            'in' => 'in',
            'dayss' => 'days',
            'deliv_add' => 'Delivery Address',
            'fee' => 'Fee',
            'deliv' => 'Delivery Place:',
            'freedeliv' => 'Free delivery if you purchase items costing over',
            'manual' => 'User Manual',
            // Add all the strings you need to translate
        ];
        break;
}
?>
